/**
 * Parse the SDK session JSONL transcript into the simplified
 * `{ role, content }[]` shape used by the conversation-archive
 * markdown renderer.
 *
 * Lives in its own module (not inline in `index.ts`) so unit tests can
 * import it without dragging the agent-SDK into the test process — same
 * pattern as `./system-prompt-assembly.ts`. The `index.ts` runtime
 * imports `@anthropic-ai/claude-agent-sdk`; pure transcript parsing
 * stays SDK-free.
 *
 * The shape mirrors what the SDK's own `getSessionMessages` returns
 * after its `BS` filter (`@anthropic-ai/claude-agent-sdk` sdk.mjs):
 * `isMeta:true`, `isSidechain:true`, and any truthy-`teamName` lines
 * are SDK-internal and never represent a real conversation turn — they
 * are skipped here for the same reason they are skipped there. The
 * exact `BS` predicate from the SDK is:
 *
 * ```js
 * function BS($,X){
 *   if($.type==="user"||$.type==="assistant");
 *   else if($.type==="system"&&X);
 *   else return!1;
 *   if($.isMeta)return!1;
 *   if($.isSidechain)return!1;
 *   if($.teamName)return!1;
 *   return!0;
 * }
 * ```
 *
 * `teamName` is added by the Task-tool / TeamCreate path: subagent
 * lines carry `teamName: "<agent-name>"` and the SDK keeps them out of
 * the parent's session view; we keep them out of the archive for the
 * same reason. (The condition is truthy-`teamName`, not `=== true`,
 * because the SDK uses the agent name itself as the marker.)
 *
 * One deliberate divergence from `BS`: this helper also skips
 * `isCompactSummary:true`. `BS` doesn't filter on it because at the
 * point `BS` runs (a session-history view) the compact summary IS a
 * real turn the model needs to see post-compaction. The conversation
 * archive serves a different purpose — a human-readable record of
 * actual user/assistant exchanges — and the synthetic compact-rollup
 * summary is rendered as `**User**: <auto-generated summary>...`
 * boilerplate that pollutes the archive without contributing real
 * dialogue. The SDK's OTHER consumer paths (the lastPrompt /
 * commandFallback extractor in sdk.mjs that finds the most recent
 * non-tool-result user message) DO skip `isCompactSummary:true`
 * alongside `isMeta:true` for the same reason — finding "the actual
 * user prompt." We follow the spirit of those consumer paths because
 * the archive is closer to "find the user's prompts" than it is to
 * "render the model's session memory."
 *
 * `isMeta:true` in particular is the tag carried by the synthetic user
 * message Claude Code injects when `excludeDynamicSections: true` is
 * set on the preset system prompt (#416). Without skipping it,
 * archived conversations would gain a `**User**: <env-info ...>`
 * boilerplate entry on every turn.
 */

export interface ParsedMessage {
  role: 'user' | 'assistant';
  content: string;
}

export function parseTranscript(content: string): ParsedMessage[] {
  const messages: ParsedMessage[] = [];

  for (const line of content.split('\n')) {
    if (!line.trim()) continue;
    let entry: unknown;
    try {
      entry = JSON.parse(line);
    } catch (err) {
      // The narrow expected failure: `JSON.parse` throws `SyntaxError`
      // on a malformed line — typically a mid-flush partial write the
      // SDK is still extending, or operator-edited junk. Skip the
      // line; the rest of the transcript still parses. Per
      // `coding-policy: error-handling`, let any other exception
      // propagate (it signals a real bug, not a transient parse).
      if (err instanceof SyntaxError) continue;
      throw err;
    }
    if (!entry || typeof entry !== 'object') continue;
    const e = entry as Record<string, unknown>;
    // Skip SDK-internal synthetic user turns. The SDK's own
    // `getSessionMessages` does the same in its `BS` filter — we match
    // it so the archive shows only real user/assistant exchanges.
    // Match the SDK's `BS` predicate exactly: `if($.isMeta)`,
    // `if($.isSidechain)`, `if($.teamName)` — truthy-checks on ANY
    // truthy value, not strict equality. Strict-equality checks
    // (e.g., `=== true`) would let a malformed-but-truthy upstream
    // emission like `isMeta: 1` or `isSidechain: "yes"` slip past us
    // even though `getSessionMessages` would hide it. Cost of the
    // false-positive (one missed real turn from a buggy emitter) is
    // lower than the cost of the false-negative (synthetic / subagent
    // / SDK-internal traffic in the archive). `isCompactSummary`
    // follows the same convention here even though `BS` doesn't
    // filter on it (see "deliberate divergence" in the docstring
    // above for why the archive does).
    if (e.isMeta) continue;
    if (e.isCompactSummary) continue;
    if (e.isSidechain) continue;
    if (e.teamName) continue;

    const type = e.type;
    const message = e.message as { content?: unknown } | undefined;
    if (!message || message.content === undefined || message.content === null) {
      continue;
    }
    const content = message.content;

    if (type === 'user') {
      const text = extractUserText(content);
      if (text) messages.push({ role: 'user', content: text });
    } else if (type === 'assistant') {
      const text = extractAssistantText(content);
      if (text) messages.push({ role: 'assistant', content: text });
    }
  }

  return messages;
}

function extractUserText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content
    .map((c) => {
      if (!c || typeof c !== 'object') return '';
      const text = (c as { text?: unknown }).text;
      return typeof text === 'string' ? text : '';
    })
    .join('');
}

function extractAssistantText(content: unknown): string {
  if (!Array.isArray(content)) return '';
  return content
    .filter((c) => {
      if (!c || typeof c !== 'object') return false;
      return (c as { type?: unknown }).type === 'text';
    })
    .map((c) => {
      const text = (c as { text?: unknown }).text;
      return typeof text === 'string' ? text : '';
    })
    .join('');
}
