#!/usr/bin/env python3
"""One-shot enrichment of existing inventory.

For each book in books.json, fetch fresh metadata from Audible API and merge
the new fields (read_status, percent_complete, series, subtitle, etc.) into
the existing record. Preserves all existing fields — only fills new ones or
updates the ones that come from Audible (rating, percent_complete, etc.).

Usage:
    python3 enrich.py [--dry-run] [--limit N] [--asin ASIN]

Mounts expected:
    /library          — audiobook library root
    /root/.audible    — audible-cli auth dir (mounted from the host's
                        ~/.audible to match the cli's default lookup)

Environment:
    AUDIOBOOK_DIR — override library path (default: /library)
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

from backup import (
    find_inventory,
    load_inventory,
    save_inventory,
    fetch_enriched_library,
    fetch_chapters,
    map_to_inventory_schema,
)


# Fields that come from Audible API and should be refreshed on enrichment.
# Everything else (filename, files, key generated by OpenAudible, etc.) is
# preserved from the existing record.
ENRICHABLE_FIELDS = {
    # Existing OpenAudible fields we can refresh
    "title", "title_short", "author", "author_link", "narrated_by",
    "publisher", "summary", "description", "copyright", "language",
    "genre", "rating_average", "rating_count", "release_date",
    "duration", "seconds", "abridged", "image_url", "info_link",
    "ayce", "read_status",
    # New extras — names must match backup.map_to_inventory_schema().
    # `series_title` here did not match the schema's `series_name` /
    # `series_sequence` / `series_link` fields so series metadata was
    # silently never refreshed on enrichment.
    "subtitle", "series_name", "series_sequence", "series_link",
    "percent_complete", "date_added", "isbn", "sku", "voice_description",
    "narration_accent", "format_type", "content_type",
    "publication_datetime",
}

# Fields where we should NOT overwrite an existing non-empty value
PRESERVE_IF_PRESENT = {
    "filename", "files", "user_id", "key", "purchase_date",
    # chapters: we already have rich chapter data in OpenAudible; only fill if missing
    "chapters",
}


def merge_enrichment(existing: dict, fresh: dict) -> dict:
    """Merge fresh metadata into existing record.

    Rules:
    - PRESERVE_IF_PRESENT: keep existing if non-empty, fill from fresh if empty
    - ENRICHABLE_FIELDS: take from fresh (it's authoritative for these)
    - Other existing fields: preserve as-is
    - New fields from `fresh` that aren't in existing: add them
    """
    merged = dict(existing)  # start with everything from existing

    for key, fresh_val in fresh.items():
        if key in PRESERVE_IF_PRESENT:
            existing_val = existing.get(key)
            # "empty" = None, "", [], 0, False — but 0 is meaningful for some
            # fields. Use a more conservative empty check.
            is_empty = (
                existing_val is None
                or existing_val == ""
                or existing_val == []
                or existing_val == {}
            )
            if is_empty:
                merged[key] = fresh_val
            # else: keep existing
        elif key in ENRICHABLE_FIELDS:
            merged[key] = fresh_val
        elif key not in merged:
            # New field that didn't exist in inventory before
            merged[key] = fresh_val
        # else: existing field not in our enrich list — leave it alone

    return merged


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="One-shot enrichment of existing inventory"
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would change, don't write")
    parser.add_argument("--limit", type=int, default=0,
                        help="Process only first N books (0 = all)")
    parser.add_argument("--asin", type=str, default="",
                        help="Process only this single ASIN (for testing)")
    parser.add_argument("--no-chapters", action="store_true",
                        help="Skip per-book chapter API call (faster)")
    parser.add_argument("--refresh-chapters", action="store_true",
                        help="Refresh chapters from Audible API even if present")
    parser.add_argument("--refresh-all", action="store_true",
                        help="Refresh ALL fields from Audible (overwrite local). "
                             "Implies --refresh-chapters. Preserves only "
                             "filename, files, m4b_path (local download paths).")
    parser.add_argument("--save-every", type=int, default=10,
                        help="Save after every N enriched books (default: 10)")
    args = parser.parse_args()

    library_dir = Path(os.environ.get("AUDIOBOOK_DIR", "/library"))
    tmp_dir = Path("/tmp/audible-backup")
    tmp_dir.mkdir(exist_ok=True)

    inventory_path = find_inventory(library_dir)
    if not inventory_path:
        print("ERROR: Inventory not found", file=sys.stderr)
        sys.exit(1)

    inventory = load_inventory(inventory_path)
    log(f"Loaded {len(inventory)} books from {inventory_path.name}")

    # Build ASIN → existing record map for fast lookup
    by_asin = {b["asin"]: b for b in inventory if b.get("asin")}
    log(f"Books with ASIN: {len(by_asin)}")

    # Filter by ASIN or limit
    if args.asin:
        targets = [b for b in inventory if b.get("asin") == args.asin]
        if not targets:
            print(f"ERROR: ASIN {args.asin} not in inventory", file=sys.stderr)
            sys.exit(1)
    else:
        targets = [b for b in inventory if b.get("asin")]
        if args.limit > 0:
            targets = targets[:args.limit]

    log(f"Will enrich {len(targets)} books")
    if args.dry_run:
        log("DRY RUN — no changes will be saved")

    # Fetch enriched library — single bulk call covers everything
    log("Fetching enriched library from Audible API...")
    library = fetch_enriched_library(tmp_dir)
    log(f"Got {len(library)} books from API")

    fresh_by_asin = {b["asin"]: b for b in library if b.get("asin")}

    # Process each target
    enriched_count = 0
    not_in_audible = 0
    chapter_added = 0
    field_diff_total: dict[str, int] = {}

    for i, existing in enumerate(targets, 1):
        asin = existing.get("asin")
        if not asin:
            continue

        api_book = fresh_by_asin.get(asin)
        if not api_book:
            log(f"[{i}/{len(targets)}] {asin} — not in current Audible library (returned/removed?)")
            not_in_audible += 1
            continue

        # Map API → schema
        fresh_record = map_to_inventory_schema(api_book)

        # Fetch chapters if missing, not skipped, or explicit refresh requested
        if not args.no_chapters:
            existing_chapters = existing.get("chapters") or []
            should_fetch = (
                not existing_chapters
                or args.refresh_chapters
                or args.refresh_all
            )
            if should_fetch:
                fresh_record["chapters"] = fetch_chapters(asin)
                if fresh_record["chapters"]:
                    chapter_added += 1
                # Be polite to Audible API
                time.sleep(0.1)
            else:
                fresh_record["chapters"] = existing_chapters

        # Merge — refresh-all overwrites everything that came from API
        if args.refresh_all:
            # Only preserve local-only fields (download paths)
            preserved = {
                k: existing.get(k)
                for k in ("filename", "files", "m4b_path")
                if existing.get(k)
            }
            merged = {**fresh_record, **preserved}
            # Also keep any existing fields not in fresh_record (custom additions)
            for k, v in existing.items():
                if k not in merged and k not in fresh_record:
                    merged[k] = v
        else:
            merged = merge_enrichment(existing, fresh_record)

        # Track what changed
        changed_fields = []
        for k, v in merged.items():
            if existing.get(k) != v:
                changed_fields.append(k)
                field_diff_total[k] = field_diff_total.get(k, 0) + 1

        if changed_fields:
            enriched_count += 1
            title = merged.get("title", "?")[:60]
            log(f"[{i}/{len(targets)}] {asin} {title} — {len(changed_fields)} fields updated")
        else:
            log(f"[{i}/{len(targets)}] {asin} — no changes")

        # Update inventory in place
        idx = inventory.index(existing)
        inventory[idx] = merged

        # Periodic save
        if not args.dry_run and i % args.save_every == 0:
            save_inventory(inventory_path, inventory)
            log(f"  ... saved progress ({i}/{len(targets)})")

    # Final save
    if not args.dry_run:
        save_inventory(inventory_path, inventory)
        log(f"Final save complete")

    # Summary
    log("")
    log("=== Enrichment Summary ===")
    log(f"Books processed: {len(targets)}")
    log(f"Books enriched: {enriched_count}")
    log(f"Books with new chapters: {chapter_added}")
    log(f"Books not in current Audible library: {not_in_audible}")
    log(f"Inventory size: {len(inventory)}")
    log("")
    log("Field update counts (top 20):")
    for field, count in sorted(field_diff_total.items(), key=lambda x: -x[1])[:20]:
        log(f"  {field}: {count}")

    # JSON summary on stdout
    print(json.dumps({
        "processed": len(targets),
        "enriched": enriched_count,
        "chapters_added": chapter_added,
        "not_in_audible": not_in_audible,
        "inventory_size": len(inventory),
        "dry_run": args.dry_run,
        "field_updates": field_diff_total,
    }, indent=2))


if __name__ == "__main__":
    main()
