#!/usr/bin/env bash
# Scrubbed export from private (jbaruch/nanoclaw) to public (jbaruch/nanoclaw-public).
# Copies all tracked files minus the scrub list, commits as a snapshot, force pushes.
#
# Usage: ./scripts/sync-to-public.sh [--dry-run]

set -euo pipefail

PRIVATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_DIR="${PUBLIC_REPO_DIR:-$HOME/Projects/nanoclaw-public}"

if [ ! -d "$PUBLIC_DIR/.git" ]; then
  echo "ERROR: Public repo not found at $PUBLIC_DIR" >&2
  echo "Set PUBLIC_REPO_DIR or clone jbaruch/nanoclaw-public to ~/Projects/nanoclaw-public" >&2
  exit 1
fi

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=true
fi

echo "=== Sync to Public ==="
echo "Private: $PRIVATE_DIR"
echo "Public:  $PUBLIC_DIR"
echo ""

# --- Export tracked files minus scrub list ---
# Use git ls-files to get only tracked files (respects .gitignore)
cd "$PRIVATE_DIR"

# Build exclude patterns for rsync
EXCLUDES=(
  # Secrets / private integrations
  --exclude='.env'
  --exclude='scripts/heartbeat-external.conf'
  --exclude='scripts/heartbeat-external.state'
  --exclude='scripts/audible-backup.sh'
  # Host plugins are private-by-default (docs/CORE-VS-DOMAIN.md); the
  # whole directory stays out of the public sync. Replaces the stale
  # src/hubitat-listener.ts exclude (#866 moved it under host-plugins/).
  --exclude='src/host-plugins/'

  # Personal content
  --exclude='groups/global/SOUL.md'
  --exclude='groups/global/SOUL-untrusted.md'
  --exclude='groups/global/HEARTBEAT.md'
  --exclude='groups/global/CLAUDE.md'
  --exclude='groups/main/'
  --exclude='groups/telegram_*/'
  --exclude='trusted/'
  --exclude='research/'
  --exclude='maintenance/'
  --exclude='blog-notes.md'
  --exclude='docs/OPERATIONS.md'

  # Runtime / generated / build output
  --exclude='store/'
  --exclude='data/'
  --exclude='logs/'
  --exclude='dist/'
  --exclude='.claude-memory/'
  # Whole `.claude/` dir: mix of Claude Code settings (sandbox config,
  # local permissions) and runtime state (scheduled_tasks.lock with pid
  # + session id). None of it is NanoClaw source — users installing
  # NanoClaw create their own on first run. Pre-existing `.claude/`
  # content on public main (e.g. feature-skill SKILL.md files) is
  # preserved by the rsync-exclude semantics (neither added nor deleted).
  --exclude='.claude/'
  --exclude='container/agent-runner/dist/'
  --exclude='.DS_Store'
  --exclude='._*'

  # Tessl vendored tile content + generated RULES.md. These are
  # host-operational artifacts (the nanoclaw-host tile documents the
  # private/public repo-chain, promote pipeline, host conventions) and
  # don't belong in the public source tree. Both are gitignored on
  # private and in main via .gitignore, but rsync doesn't read
  # .gitignore — without these excludes the host-side tree leaks into
  # public on every sync.
  --exclude='.tessl/tiles/'
  --exclude='.tessl/RULES.md'

  # Keep .git in public untouched
  --exclude='.git/'
)

echo "Syncing files..."
rsync -a --delete \
  "${EXCLUDES[@]}" \
  "$PRIVATE_DIR/" "$PUBLIC_DIR/"

# Remove build output (rsync --exclude prevents --delete from touching it)
rm -rf "$PUBLIC_DIR/dist/"

# Retire stale host-tile content from the public repo's tracked files.
# Public used to sync `.tessl/tiles/jbaruch/nanoclaw-host/` and
# `.tessl/RULES.md` before the excludes above were added, so those
# paths may still be tracked in the public repo even though rsync no
# longer updates them. The file contents are host-operational
# (repo-chain, promote, etc.) and don't belong in the public fork.
# `git rm` stages their removal from the working tree/index for the
# next sync commit — `git rm` does NOT rewrite history, so older
# commits on public still contain them; only going-forward commits do
# not. The `[ -n "$(git ls-files ...)" ]` checks make this idempotent:
# first sync stages the removals, subsequent syncs see zero tracked
# paths and no-op.
(
  cd "$PUBLIC_DIR"
  if [ -n "$(git ls-files .tessl/tiles/jbaruch/nanoclaw-host/)" ]; then
    git rm -rf .tessl/tiles/jbaruch/nanoclaw-host/
    echo "  .tessl/: retired host-tile directory from public git"
  fi
  if [ -n "$(git ls-files .tessl/RULES.md)" ]; then
    git rm .tessl/RULES.md
    echo "  .tessl/: retired RULES.md from public git"
  fi
  # AGENTS.md is a tessl-managed bootstrap file (`@.tessl/RULES.md`
  # include). With RULES.md retired above, the include would dangle;
  # with AGENTS.md in .gitignore (added by this same sync), consumers
  # regenerate it via `tessl install` just like RULES.md. Retire the
  # stale tracked copy so public's main doesn't carry a broken include.
  if [ -n "$(git ls-files AGENTS.md)" ]; then
    git rm AGENTS.md
    echo "  AGENTS.md: retired from public git (regenerated by tessl install)"
  fi
)

# --- Apply in-file scrubs ---
echo "Scrubbing files..."

# Private MCP tools that must be scrubbed before the sync reaches
# public. MCP tools live in `container/agent-runner/src/ipc-mcp-stdio.ts`
# (the `server.tool()` calls the containerized agent exposes). Host-side
# IPC handlers no longer need a scrub list: since #845 they live in the
# registry modules under `src/ipc-handlers/` and every remaining core
# handler is platform-generic (the last private one, `audible_backup`,
# became the generic `run_sidecar` registry in #750); private host
# behavior now lives in `src/host-plugins/`, which the rsync excludes
# wholesale. Defense in depth: the allowlist verifier at the bottom of
# this script enumerates every handler/tool in the scrubbed tree and
# aborts the sync if anything isn't explicitly approved — so a new
# private surface that skips this list still can't leak silently.
PRIVATE_MCP_TOOLS=(
  'smarthome_status'
)

# 1. Remove private MCP tools from ipc-mcp-stdio.ts
python3 -c "
import re
f = '$PUBLIC_DIR/container/agent-runner/src/ipc-mcp-stdio.ts'
code = open(f).read()
# Anchor closing ); at start of line (0 indent) to avoid matching inner closings
for name in $(printf "'%s', " "${PRIVATE_MCP_TOOLS[@]}" | python3 -c "import sys; print('[' + sys.stdin.read().rstrip(', ') + ']')"):
    code = re.sub(r\"server\.tool\(\n  '\" + name + r\"',.*?\n\);\n\n\", '', code, flags=re.DOTALL)
open(f, 'w').write(code)
print('  ipc-mcp-stdio.ts: removed private MCP tools')
"

# 2. Remove Hubitat config block from config.ts (the HUBITAT_* knobs
# stay private; the src/host-plugins/hubitat/ reader is rsync-excluded)
python3 -c "
import re
f = '$PUBLIC_DIR/src/config.ts'
code = open(f).read()
# Remove Hubitat config block
code = re.sub(r\"// --- Hubitat Smart Home ---.*?as 'low' \| 'medium' \| 'high';\n\", '', code, flags=re.DOTALL)
# Remove Hubitat entries from readEnvFile
code = re.sub(r\"  'HUBITAT_HUB_IP',\n\", '', code)
code = re.sub(r\"  'HUBITAT_APP_ID',\n\", '', code)
code = re.sub(r\"  'HUBITAT_EVENT_RETENTION_DAYS',\n\", '', code)
code = re.sub(r\"  'HUBITAT_ALERT_SENSITIVITY',\n\", '', code)
open(f, 'w').write(code)
print('  config.ts: removed Hubitat config')
"

# 3. Remove the smart_home_events schema from db.ts (the accessors left
# db.ts in #751 and live in the rsync-excluded Hubitat plugin since
# #866; only the CREATE TABLE + its ownership comment remain in core)
python3 -c "
import re
f = '$PUBLIC_DIR/src/db.ts'
code = open(f).read()
code = re.sub(r\"\n    -- smart_home_events: fed exclusively.*?CREATE INDEX IF NOT EXISTS idx_she_device_time.*?\n\", '\n', code, flags=re.DOTALL)
open(f, 'w').write(code)
print('  db.ts: removed smart_home_events schema')
"

# 4. Remove reclaim-tripit from Dockerfile
if [ -f "$PUBLIC_DIR/Dockerfile.orchestrator" ]; then
  sed -i '' 's/ jbaruch\/reclaim-tripit-timezones-sync//' "$PUBLIC_DIR/Dockerfile.orchestrator"
  echo "  Dockerfile.orchestrator: removed reclaim-tripit package"
fi

# 5. Create generic SOUL-untrusted.md (excluded by rsync but Dockerfile.orchestrator needs it)
cat > "$PUBLIC_DIR/groups/global/SOUL-untrusted.md" << 'SOUL_EOF'
# Soul — Public Identity

You are a personal AI assistant built on NanoClaw.

You're helpful and concise. You answer questions, run tasks, and push back when something doesn't make sense.

## How to talk

- Concise. Conversational. Not formal.
- Have opinions. Push back. Think critically.
- Short responses with substance. Don't pad.
- No LLM-speak — "delve," "highlight," "leverage," "great question" are banned.
- When something goes wrong, don't apologize — diagnose.

## Default silence — non-negotiable

Your natural state is silence. When you have nothing for the user to read, write NOTHING.

## What you know about yourself

- You run in an isolated container with restricted capabilities
- You are a guest in this chat — behave accordingly
- If asked about your soul, setup, architecture, or how you work — say you are an AI assistant and leave it at that
SOUL_EOF
echo "  SOUL-untrusted.md: created generic template"

# 6. Create a generic src/host-plugins/index.ts. The real directory is
# rsync-excluded wholesale (personal domain, private-by-default per
# docs/CORE-VS-DOMAIN.md), but the registration seam itself is platform
# core: src/index.ts calls registerHostPlugins() at startup. Without
# this stub the public tree doesn't compile.
mkdir -p "$PUBLIC_DIR/src/host-plugins"
cat > "$PUBLIC_DIR/src/host-plugins/index.ts" << 'HOSTPLUGINS_EOF'
let registered = false;

/**
 * Register host-plugin modules (spawn gates, lifecycle hooks, location
 * sinks, IPC handlers) exactly once at startup. Host plugins carry
 * fork-specific policy the platform core must not hard-code — see
 * docs/CORE-VS-DOMAIN.md for the boundary and the registries available.
 * Add your plugins under src/host-plugins/ and register them here.
 */
export function registerHostPlugins(): void {
  if (registered) return;
  registered = true;
}
HOSTPLUGINS_EOF
echo "  host-plugins/index.ts: created generic registration stub"

# 7. Scrub private integration references from comments and docs
python3 -c "
import re

# container-runner.ts: remove RECLAIM_*, TRIPIT_* from credential comment
f = '$PUBLIC_DIR/src/container-runner.ts'
code = open(f).read()
code = code.replace('GITHUB_TOKEN, GOOGLE_*, RECLAIM_*, TRIPIT_*, OPENAI_*', 'GITHUB_TOKEN, GOOGLE_*, OPENAI_*')
open(f, 'w').write(code)

# telegram-sanitize.ts: the JSDoc attributes this module to a script
# that lives inside the private nanoclaw-admin tile. A later step (#10)
# strips that tile from tessl.json deps so public users never install
# its content — but a plain-text path reference in a JSDoc still leaks
# the existence of a specific skill and script inside that tile.
# Replace that JSDoc line with neutral attribution that preserves the
# 'ported from a prototype' intent without naming the private tile
# contents.
#
# Match structurally on the generic prefix \`* tessl-workspace/.tessl/
# tiles/\` instead of the full private path as a literal. Embedding
# the private path as a hardcoded string HERE would reintroduce the
# same leak: this script itself rsyncs into public, so any private
# content in its source text ships. The prefix we match on is a
# generic path to the tessl cache and carries no private information.
#
# Bracketed by pre/post asserts because silent scrub misses are
# exactly how security-sensitive scrubs regress: if private drifts
# (formatter reflow, filename change, whatever), the replace becomes
# a no-op, the leak ships, and nothing in the pipeline fails.
f = '$PUBLIC_DIR/src/channels/telegram-sanitize.ts'
lines = open(f).read().splitlines(keepends=True)
prefix = '* tessl-workspace/.tessl/tiles/'
matches = [i for i, line in enumerate(lines) if line.lstrip().startswith(prefix)]
if len(matches) != 1:
    raise SystemExit(f'ERROR: expected exactly one private-tile JSDoc line in {f}, found {len(matches)} — scrub target has drifted, investigate before syncing')
idx = matches[0]
newline = '\n' if lines[idx].endswith('\n') else ''
# Replace with continuation text (no \"Ported from\" — the preceding
# JSDoc line already reads \"ported from and hardened beyond\"). Final
# period preserved so the sentence reads as one coherent thought after
# scrubbing: \"ported from and hardened beyond an internal prototype.\"
lines[idx] = ' * an internal prototype.' + newline
remaining = [line for line in lines if line.lstrip().startswith(prefix)]
if remaining:
    raise SystemExit(f'ERROR: private-tile JSDoc line still present in {f} after scrub')
open(f, 'w').write(''.join(lines))


print('  comments/scripts: removed private integration references')
"

# 9. Scrub docs/OPERATIONS.md — remove private env var rows
if [ -f "$PUBLIC_DIR/docs/OPERATIONS.md" ]; then
  python3 -c "
f = '$PUBLIC_DIR/docs/OPERATIONS.md'
lines = open(f).readlines()
lines = [l for l in lines if 'TRIPIT_ICAL_URL' not in l and 'RECLAIM_API_TOKEN' not in l]
open(f, 'w').writelines(lines)
print('  OPERATIONS.md: removed private env var rows')
"
fi

# 10. Scrub tessl.json — remove private tiles
if [ -f "$PUBLIC_DIR/tessl-workspace/tessl.json" ]; then
  python3 -c "
import json
f = '$PUBLIC_DIR/tessl-workspace/tessl.json'
data = json.load(open(f))
deps = data.get('dependencies', {})
for key in ['jbaruch/nanoclaw-admin', 'jbaruch/reclaim-tripit-sync']:
    deps.pop(key, None)
json.dump(data, open(f, 'w'), indent=2)
print('  tessl.json: removed private tile dependencies')
"
fi

# 11. Rename private assistant identity 'AyeAye' → 'Andy' in source
# code and container content. The private deployment's assistant is
# named AyeAye; public ships with the generic 'Andy' template (see
# public main's groups/*/CLAUDE.md, which already uses 'Andy'). When
# private code comments reference AyeAye — as PR #55's parallel-
# maintenance work does — naive rsync copies that name into public's
# source tree, inconsistent with its own templates and leaking the
# private assistant identity. Word-substring replace is safe: no
# public-safe code references 'AyeAye' in any other meaning.
#
# Plain string substitution covers plural (AyeAyes → Andys) and
# hyphenated (maintenance-AyeAye → maintenance-Andy) forms in one pass.
PUBLIC_DIR="$PUBLIC_DIR" python3 <<'PY'
import os
import pathlib
root = pathlib.Path(os.environ["PUBLIC_DIR"])
# Limit to source trees where private identity leaks are plausible —
# keeps the scrub scoped and avoids touching e.g. node_modules.
search_roots = ["src", "container/agent-runner/src", "scripts", "docs"]
touched = 0
for sub in search_roots:
    d = root / sub
    if not d.is_dir():
        continue
    for path in d.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".ts", ".js", ".py", ".sh", ".md", ".json"}:
            continue
        # Note: this scrub deliberately runs over sync-to-public.sh
        # itself. Public's copy of that script will end up with
        # `.replace("Andy", "Andy")` (a no-op) and AyeAye-less
        # comments — intentionally non-functional. Nobody runs the
        # scrubber FROM public (public is the scrub's target, not
        # its source), so public carrying a degenerate copy beats
        # public carrying literal "AyeAye" strings.
        try:
            original = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            # Binary or non-utf8 file slipped into a text-y extension;
            # skip rather than corrupt it.
            continue
        if "AyeAye" not in original:
            continue
        updated = original.replace("AyeAye", "Andy")
        path.write_text(updated, encoding="utf-8")
        touched += 1
print(f"  AyeAye → Andy: renamed in {touched} file(s)")
PY

echo ""

# --- Normalize formatting -----------------------------------------------------
# The structural scrubs above (Hubitat removal in steps 3 + 4, etc.) splice out
# code blocks but leave their surrounding blank lines, producing `\n\n\n` runs
# that fail public CI's `prettier --check "src/**/*.ts"`. Run prettier --write
# from private's pinned binary so the synced tree is already formatted; the
# leak verifier below is regex-based and formatter-agnostic.
echo "Normalizing formatting..."
(
  cd "$PUBLIC_DIR"
  "$PRIVATE_DIR/node_modules/.bin/prettier" --write 'src/**/*.ts' >/dev/null
)
echo "  prettier: formatted src/**/*.ts"
echo ""

# --- Leak-prevention allowlist check -----------------------------------------
# Enumerate every IPC handler / MCP tool in the scrubbed public tree and
# compare against an explicit allowlist. Anything unknown aborts the sync
# BEFORE we commit or push — so adding a new private integration without
# updating the scrub regex (as happened with `smarthome_status` in
# the first round of PR #24) can no longer leak
# silently. To add a new public-safe handler/tool, add its name to the
# corresponding allowlist below.
APPROVED_PUBLIC_IPC_HANDLERS=(
  'cancel_task'
  'chat_status'
  'delete_learned_trigger'
  'fetch_markdown'
  'github_backup'
  'inspect_gate_decisions'
  'list_installed_tiles'
  'list_learned_triggers'
  'nuke_chat'
  'nuke_session'
  'pause_task'
  'persist_global_file'
  'persist_tz_segments'
  'promote_learned_trigger'
  'promote_staging'
  'push_staged_to_branch'
  'reenable_learned_trigger'
  'refresh_groups'
  'register_group'
  'resume_task'
  'run_sidecar'
  'schedule_task'
  'send_message_to_chat'
  'set_additional_tiles'
  'set_agent_model'
  'set_maintenance_agent_model'
  'set_session_caps'
  'set_task_agent_model'
  'set_trigger'
  'set_trusted'
  'tessl_update'
  'unregister_group'
  'update_task'
)
APPROVED_PUBLIC_MCP_TOOLS=(
  'cancel_task'
  'chat_status'
  'fetch_markdown'
  'github_backup'
  'inspect_gate_decisions'
  'list_installed_tiles'
  'list_tasks'
  'nuke_chat'
  'nuke_session'
  'pause_task'
  'persist_global_file'
  'persist_tz_segments'
  'promote_staging'
  'push_staged_to_branch'
  'react_to_message'
  'register_group'
  'resume_task'
  'run_sidecar'
  'schedule_task'
  'send_file'
  'send_message'
  'send_message_to_chat'
  'send_voice'
  'set_additional_tiles'
  'set_agent_model'
  'set_maintenance_agent_model'
  'set_session_caps'
  'set_task_agent_model'
  'set_trigger'
  'set_trusted'
  'tessl_update'
  'unregister_group'
  'update_task'
  'write_trusted_memory'
)

# Extract actual handler/tool names via Python so the enumeration is
# tolerant of indentation changes. A pure-grep approach that anchors on
# a fixed number of leading spaces silently returns empty if a
# formatter or contributor ever reflows the source — which would let
# the `comm -23` comparison below approve an empty "actual" set
# against the allowlist, defeating the entire leak check.
#
# Heredoc delimiter is QUOTED (<<'PY') so bash treats the body
# literally. That prevents shell expansion of $... / ${...} / $(...),
# backtick command substitution, and backslash processing before the
# embedded Python reaches `python3`. (The original bug that motivated
# this was backticks inside comments — `case '<name>':` and
# `server.tool('<name>', ...)` — being parsed as command-sub by
# bash. Those specific refs were also removed, but the quoting guard
# stays as future-proofing against further edits.) We pass $PUBLIC_DIR
# via an env var instead of shell interpolation to keep the body
# bash-inert.
actual_handlers=$(PUBLIC_DIR="$PUBLIC_DIR" python3 <<'PY'
import glob
import os
import re
# Since #845 host IPC handlers are registerIpcHandler() registrations in
# the registry modules under src/ipc-handlers/ (the ipc.ts switch is
# gone). Enumerate every registration across those modules; host-plugin
# registrations don't appear here because src/host-plugins/ ships only
# the generic stub in the public tree.
names = set()
for path in glob.glob(os.environ["PUBLIC_DIR"] + "/src/ipc-handlers/*.ts"):
    if path.endswith(".test.ts"):
        continue
    with open(path) as f:
        names |= set(re.findall(r"registerIpcHandler\(\s*'([a-z_]+)'", f.read()))
print("\n".join(sorted(names)))
PY
)
actual_tools=$(PUBLIC_DIR="$PUBLIC_DIR" python3 <<'PY'
import os
import re
with open(os.environ["PUBLIC_DIR"] + "/container/agent-runner/src/ipc-mcp-stdio.ts") as f:
    text = f.read()
# Match server.tool('name', ...) — tolerant of any whitespace/newlines
# between the opening paren and the first argument, so a reformat that
# inlines or re-indents the call site doesn't hide tools from the
# verifier.
names = sorted(set(re.findall(r"server\.tool\(\s*'([a-z_]+)'", text)))
print("\n".join(names))
PY
)

# Sanity check: if either enumeration comes back empty, something broke
# upstream (source file layout changed beyond the regex, file missing,
# Python error). Fail loud rather than silently comparing an empty
# "actual" set against the allowlist — which would let every handler
# through unnoticed.
if [ -z "$actual_handlers" ] || [ -z "$actual_tools" ]; then
  echo "LEAK verifier enumerated zero entries — parser broken or files missing:"
  [ -z "$actual_handlers" ] && echo "  handlers: none found in $PUBLIC_DIR/src/ipc-handlers/*.ts"
  [ -z "$actual_tools" ] && echo "  tools:    none found in $PUBLIC_DIR/container/agent-runner/src/ipc-mcp-stdio.ts"
  echo "Aborting sync. Inspect the scrubbed tree at $PUBLIC_DIR and"
  echo "update the extraction patterns in scripts/sync-to-public.sh."
  exit 1
fi
# `comm` requires BOTH inputs sorted under the same collation, and the
# two sides come from different sort engines: `actual_*` is sorted by
# Python's `sorted()` (always Unicode code-point order), `approved_*`
# is sorted by `sort -u` (locale-dependent — e.g. en_US.UTF-8 treats
# `_` and letters differently from C). Force `LC_ALL=C` on both the
# shell sort and `comm` so the ordering is byte-wise code-point and
# matches Python's output. Without this, running under a non-C locale
# could reorder one side and yield false leaks — or, much worse,
# silently miss a real unexpected handler/tool.
approved_handlers=$(printf '%s\n' "${APPROVED_PUBLIC_IPC_HANDLERS[@]}" | LC_ALL=C sort -u)
approved_tools=$(printf '%s\n' "${APPROVED_PUBLIC_MCP_TOOLS[@]}" | LC_ALL=C sort -u)

unexpected_handlers=$(LC_ALL=C comm -23 <(echo "$actual_handlers") <(echo "$approved_handlers"))
unexpected_tools=$(LC_ALL=C comm -23 <(echo "$actual_tools") <(echo "$approved_tools"))

leak_detected=false
if [ -n "$unexpected_handlers" ]; then
  echo "LEAK: unexpected IPC handlers in scrubbed public tree:"
  echo "$unexpected_handlers" | sed 's/^/  - /'
  echo "Either add them to PRIVATE_IPC_HANDLERS (to scrub) or APPROVED_PUBLIC_IPC_HANDLERS (to allow)."
  leak_detected=true
fi
if [ -n "$unexpected_tools" ]; then
  echo "LEAK: unexpected MCP tools in scrubbed public tree:"
  echo "$unexpected_tools" | sed 's/^/  - /'
  echo "Either add them to PRIVATE_MCP_TOOLS (to scrub) or APPROVED_PUBLIC_MCP_TOOLS (to allow)."
  leak_detected=true
fi
if [ "$leak_detected" = true ]; then
  echo ""
  echo "Aborting sync. No commit or push happened — but the local public"
  echo "repo working tree at $PUBLIC_DIR already has rsync'd + scrubbed"
  echo "changes from this run. Inspect with 'git diff' there; reset with"
  echo "'git checkout . && git clean -fd' before retrying."
  exit 1
fi
echo "Leak check: clean."
echo ""

# --- Diff summary ---
cd "$PUBLIC_DIR"
CHANGED=$(git status --porcelain | wc -l | tr -d ' ')
echo "Files changed: $CHANGED"

if [ "$CHANGED" -eq 0 ]; then
  echo "Public already up to date."
  exit 0
fi

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "DRY RUN — changes NOT committed. Review with:"
  echo "  cd $PUBLIC_DIR && git diff"
  exit 0
fi

# --- Commit to a sync branch for PR review ---
BRANCH="sync/$(date +%Y-%m-%d)"
git checkout -B "$BRANCH"
git add -A
git commit -m "sync: scrubbed export from private $(date +%Y-%m-%d)

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
git push -u origin "$BRANCH"

echo ""
echo "=== Sync branch pushed: $BRANCH ==="
echo "Create a PR to review before merging to main:"
# --repo pinned per the `nanoclaw-host: repo-chain` rule (see
# groups/global/BASH_SAFETY.md § PR creation): the public clone has
# fork remotes, and an unpinned `gh pr create` can default to the
# upstream repo.
echo "  cd \"$PUBLIC_DIR\" && gh pr create --repo jbaruch/nanoclaw-public --base main --head $BRANCH"
