/**
 * Sync live group state into `groups/<source-group>/backup-repo/` for
 * the `github_backup` pipeline.
 *
 * Policy: back up everything under `groups/` that the agent / runtime
 * mutates and that is NOT reproducible from a fresh deploy (`git pull`
 * of the nanoclaw repo) or from `tessl install`.
 *
 * Layout inside `backup-repo/`:
 *
 *   backup-repo/
 *     global/<files…>            mirror of groups/global/
 *     groups/<name>/<files…>     mirror of groups/<name>/ for each
 *                                non-hidden group dir (except global)
 *     state/<table>.sql          per-table SQLite dumps
 *
 * Mirror is delete-on-missing within `global/` and `groups/`: files
 * that disappear from the source are removed from the dest so the
 * working tree reflects live state. Git history retains the older
 * state.
 *
 * Denied paths (skipped on copy, applied at any depth):
 *
 *   Directories: backup-repo, .tessl, .claude, node_modules, dist,
 *                logs, tmp, conversations, .checkpoints, .archive*
 *   Files: *.lock, .tmp-*, scripts.new.*, scripts.version.*,
 *          *.bak[-.]20YY*, *.migrated-20YY*
 *
 * Reasoning: `.tessl/` and `.claude/` are regenerated by
 * `tessl install`; `node_modules/`/`dist/` are build output;
 * `logs/`/`tmp/`/`.checkpoints/` are runtime scratch; `conversations/`
 * is pre-compaction transcript archive (large, growing — agent can
 * regenerate reasoning on demand); `.archive*` is already-archived
 * state; `*.bak-*`/`*.migrated-*` are one-shot snapshots of replaced
 * state; `backup-repo` is THIS directory (recursion guard).
 */
import fs from 'fs';
import path from 'path';

import { runDumpPlan } from './db-dump.js';

export interface SyncResult {
  /** POSIX paths under backup-repo/ that were written or overwritten. */
  copied: string[];
  /** POSIX paths under backup-repo/ removed (orphans, denied content, or legacy). */
  removed: string[];
  /** Tables whose `.dump` SQL was written to backup-repo/state/<table>.sql. */
  dumped: string[];
  /** Tables in STATE_TABLES that didn't exist in the DB and were skipped. */
  skipped: string[];
}

const DENY_DIRNAMES: ReadonlySet<string> = new Set([
  'backup-repo',
  '.tessl',
  '.claude',
  'node_modules',
  'dist',
  'logs',
  'tmp',
  'conversations',
  '.checkpoints',
]);

function isDenyDir(name: string): boolean {
  if (DENY_DIRNAMES.has(name)) return true;
  if (name.startsWith('.archive')) return true; // .archives, .archive-…
  return false;
}

// File-name patterns. Anchored where appropriate so substrings inside
// legitimate filenames don't accidentally trip the denylist.
const DENY_FILE_PATTERNS: readonly RegExp[] = [
  /\.lock$/,
  /^\.tmp-/,
  /^scripts\.new\./,
  /^scripts\.version\./,
  /\.bak[-.]20\d{2}/, // foo.bak-2026-04-27, foo.bak.2026-05-08
  /\.migrated-20\d{2}/, // calendar-state.json.migrated-2026-05-01
];

function isDenyFile(name: string): boolean {
  return DENY_FILE_PATTERNS.some((re) => re.test(name));
}

// One-time legacy paths from the pre-multi-group layout. The original
// sync put telegram_swarm's content at the ROOT of backup-repo
// (MEMORY.md, blog-notes.md, memory/) and a handful of stale trees
// (skills/, trusted/, trusted-staging/) that no live pipeline updates.
// Sweeping them here converges the working tree on the new layout on
// the first run; subsequent runs find nothing to do (idempotent).
const LEGACY_PATHS_TO_REMOVE: readonly string[] = [
  'MEMORY.md',
  'daily_discoveries.md',
  'blog-notes.md',
  'memory',
  'skills',
  'trusted',
  'trusted-staging',
];

function listFilesRecursive(
  root: string,
  base: string,
  applyDenylist: boolean,
): string[] {
  const out: string[] = [];
  if (!fs.existsSync(root)) return out;
  const entries = fs.readdirSync(root, { withFileTypes: true });
  for (const e of entries) {
    const rel = base ? path.join(base, e.name) : e.name;
    if (e.isDirectory()) {
      if (applyDenylist && isDenyDir(e.name)) continue;
      out.push(
        ...listFilesRecursive(path.join(root, e.name), rel, applyDenylist),
      );
    } else if (e.isFile()) {
      if (applyDenylist && isDenyFile(e.name)) continue;
      out.push(rel);
    }
    // Symlinks and other Dirent types are intentionally skipped — the
    // mirror only round-trips plain files. Throwing here would block
    // the whole backup over a single oddly-typed entry.
  }
  return out;
}

function toPosix(prefix: string, rel: string): string {
  const parts = rel.split(path.sep);
  return prefix ? [prefix, ...parts].join('/') : parts.join('/');
}

function mirrorSubtree(
  srcDir: string,
  destDir: string,
  destPrefix: string,
  result: SyncResult,
  expected: Set<string>,
): void {
  if (!fs.existsSync(srcDir)) return;
  fs.mkdirSync(destDir, { recursive: true });
  for (const rel of listFilesRecursive(srcDir, '', true)) {
    fs.mkdirSync(path.dirname(path.join(destDir, rel)), { recursive: true });
    fs.copyFileSync(path.join(srcDir, rel), path.join(destDir, rel));
    const posix = toPosix(destPrefix, rel);
    result.copied.push(posix);
    expected.add(posix);
  }
}

function sweepOrphans(
  backupDir: string,
  prefixes: readonly string[],
  expected: ReadonlySet<string>,
  result: SyncResult,
): void {
  for (const prefix of prefixes) {
    const dir = path.join(backupDir, prefix);
    if (!fs.existsSync(dir)) continue;
    // Scan dest with denylist DISABLED — a previously-mirrored file
    // that newly matches the denylist (e.g. an old `.bak-2026-` file
    // that pre-dates this rule) must be sweepable. The denylist gates
    // COPIES from src, not removals from dest.
    for (const rel of listFilesRecursive(dir, '', false)) {
      const posix = toPosix(prefix, rel);
      if (!expected.has(posix)) {
        fs.unlinkSync(path.join(dir, rel));
        result.removed.push(posix);
      }
    }
  }
}

function removeLegacyPaths(backupDir: string, result: SyncResult): void {
  for (const rel of LEGACY_PATHS_TO_REMOVE) {
    const p = path.join(backupDir, rel);
    if (!fs.existsSync(p)) continue;
    const stat = fs.statSync(p);
    if (stat.isDirectory()) {
      const files = listFilesRecursive(p, '', false);
      fs.rmSync(p, { recursive: true });
      for (const sub of files) result.removed.push(toPosix(rel, sub));
    } else {
      fs.unlinkSync(p);
      result.removed.push(rel);
    }
  }
}

export function syncBackupRepo(args: {
  groupsRoot: string;
  backupDir: string;
  dbPath: string;
}): SyncResult {
  if (!fs.existsSync(args.groupsRoot)) {
    throw new Error(
      `backup-sync: groups root not found at ${args.groupsRoot} — verify GROUPS_DIR resolves to the expected path`,
    );
  }
  if (!fs.existsSync(args.backupDir)) {
    throw new Error(
      `backup-sync: backup-repo not found at ${args.backupDir} — clone the backup branch into this path before running github_backup`,
    );
  }

  const result: SyncResult = {
    copied: [],
    removed: [],
    dumped: [],
    skipped: [],
  };

  removeLegacyPaths(args.backupDir, result);

  const expected = new Set<string>();

  mirrorSubtree(
    path.join(args.groupsRoot, 'global'),
    path.join(args.backupDir, 'global'),
    'global',
    result,
    expected,
  );

  // Iterate every non-hidden subdir of groups/ as a group, except the
  // `global` dir already handled above. Hidden entries (`.archives`,
  // `.DS_Store`, etc.) and non-directories are skipped at the source;
  // the denylist further filters their *contents* if they get walked
  // into via nested paths (defense in depth).
  const entries = fs.readdirSync(args.groupsRoot, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (e.name.startsWith('.')) continue;
    if (e.name === 'global') continue;
    mirrorSubtree(
      path.join(args.groupsRoot, e.name),
      path.join(args.backupDir, 'groups', e.name),
      `groups/${e.name}`,
      result,
      expected,
    );
  }

  sweepOrphans(args.backupDir, ['global', 'groups'], expected, result);

  const dumpReport = runDumpPlan({
    dbPath: args.dbPath,
    outDir: path.join(args.backupDir, 'state'),
  });
  result.dumped = dumpReport.dumped;
  result.skipped = dumpReport.skipped;

  return result;
}
